### ISSUE TITLE
Question about the error result on same dataset

### ISSUE THREAD

**Issue by Edda1024** [hku-mars/LiDAR_IMU_Init#30]
Hi,I would like to ask about the error result happened on the same example,with only the pandar.yaml cut_frame_num changed from 3 to 5,and i ran the example datasets Hesai_apartment .bag four times,half of them are similarity but the other got greater error,is this normal or it is just i got  misoperation on it?

test_1
>Rotation LiDAR to IMU (degree)     =   -0.241604   -1.687440 -179.091635
Translation LiDAR to IMU (meter)   =  0.145349 -0.008220  0.090981
Time Lag IMU to LiDAR (second)     = 50574455.968229
Bias of Gyroscope  (rad/s)         =  0.000944  0.000996 -0.009290
Bias of Accelerometer (meters/s^2) = -0.011033 -0.002588  0.006981
Gravity in World Frame(meters/s^2) = -0.005756 -0.149470 -9.813815

test_2

>Rotation LiDAR to IMU (degree)     =   -0.249946   -1.651366 -178.979471
Translation LiDAR to IMU (meter)   = 0.150331 0.009933 0.127421
Time Lag IMU to LiDAR (second)     = 50574455.967223
Bias of Gyroscope  (rad/s)         =  0.002463  0.002442 -0.009575
Bias of Accelerometer (meters/s^2) = -0.009360 -0.007472  0.012774
Gravity in World Frame(meters/s^2) = -0.002329 -0.141623 -9.812926

test_3
>Rotation LiDAR to IMU (degree)     =   -0.259932   -1.650320 -178.974883
Translation LiDAR to IMU (meter)   = 0.151692 0.009458 0.126087
Time Lag IMU to LiDAR (second)     = 50574455.967253
Bias of Gyroscope  (rad/s)         =  0.002455  0.002393 -0.009571
Bias of Accelerometer (meters/s^2) = -0.009517 -0.007391  0.012698
Gravity in World Frame(meters/s^2) = -0.002563 -0.140811 -9.812829

test_4
>Rotation LiDAR to IMU (degree)     =   -0.241604   -1.687440 -179.091635
Translation LiDAR to IMU (meter)   =  0.145349 -0.008220  0.090981
Time Lag IMU to LiDAR (second)     = 50574455.968229
Bias of Gyroscope  (rad/s)         =  0.000944  0.000996 -0.009290
Bias of Accelerometer (meters/s^2) = -0.011033 -0.002588  0.006981
Gravity in World Frame(meters/s^2) = -0.005756 -0.149470 -9.813815

**Comment by zfc-zfc** [comment]
Of course changing cut_frame_num would get different results. But the rotation difference is less than 0.2°, translation difference of X and Y axis is less than 1 cm. Translation of Z axis is a little bit larger because the observability along this direction is smaller (pointcloud measurements on this direction is less). So I think your test result is normal and acceptable.
Besides, even if you don't change any parameters and run the same data twice, the results won't be totally the same because the pointcloud downsample and nearest search is random to some extent.
